# Generated by Django 3.2.18 on 2023-02-16 15:28

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import ngo_index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'Environment'), (2, 'Sports'), (3, 'Medical'), (4, 'Disaster relief'), (5, 'Anti-corruption'), (6, 'Peace'), (7, 'Humanitarian'), (8, 'Technology'), (9, 'Education'), (10, 'Regulatory'), (11, 'Religious'), (12, 'Ethics'), (13, 'Policy'), (14, 'Governance'), (15, 'Youth'), (16, 'Legal'), (17, 'Democracy'), (18, 'Other')], default=18, validators=[ngo_index.models.validate_type])),
                ('founded', models.DateField()),
                ('founders', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('staff', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('region', models.IntegerField(choices=[(1, 'Worldwide'), (2, 'Europe'), (3, 'North America'), (4, 'Central America'), (5, 'South America'), (6, 'Asia'), (7, 'Africa'), (8, 'Oceania'), (9, 'Middle East')], default=1, validators=[ngo_index.models.validate_region])),
                ('location', models.CharField(max_length=200)),
                ('headquarters', models.CharField(max_length=200)),
                ('website', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('purpose', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Non-governmental organisation',
                'ordering': ['-founded'],
            },
        ),
    ]
