# Generated by Django 3.2.18 on 2023-02-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
